services:
  db:
    image: postgres:15-alpine
    container_name: pg15-library
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-biblioteca_db}
    volumes:
      - pg_data_library:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_SSLMODE: disable
    depends_on:
      - db

volumes:
  pg_data_library:
