services:
  db:
    image: postgres:15-alpine
    container_name: pg15-library
    ports:
      - "6000:5432"
    environment:
      POSTGRES_USER: lain
      POSTGRES_PASSWORD: lain123
      POSTGRES_DB: librarydb
    volumes:
      - pg_data_library:/var/lib/postgresql/data

volumes:
  pg_data_library:
